name: Build Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
            
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Source Build Env
        id: source-build-env
        run: |
          cat ./build.env >> $GITHUB_ENV
          echo "APPS_JSON_BASE64=$(base64 -w 0 ./apps.json)" >> $GITHUB_ENV

      - name: Check disk space
        run: df -h

      - uses: actions/checkout@v4
        with:
          repository: frappe/frappe_docker
          path: builds

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          no-cache: true
          push: true
          context: builds
          file: builds/images/custom/Containerfile
          tags: ${{ secrets.DOCKER_USER }}/frappe-withapps:v15,${{ secrets.DOCKER_USER }}/frappe-withapps:latest
          build-args: |
            "progress=plain"
            "FRAPPE_PATH=${{ env.FRAPPE_REPO }}"
            "FRAPPE_BRANCH=${{ env.FRAPPE_VERSION }}"
            "PYTHON_VERSION=${{ env.PY_VERSION }}"
            "NODE_VERSION=${{ env.NODEJS_VERSION }}"
            "APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}"
